name: Dependency review

on:
  pull_request:
  schedule:
    # Run every monday at 12:00 UTC
    - cron: 0 12 * * 1

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Dependency review
        uses: actions/dependency-review-action@v3
